apiVersion: v1
kind: Service
metadata:
  name: auth-backend-service
  namespace: auth-app
  labels:
    app: auth-backend
spec:
  selector:
    app: auth-backend
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30002
    protocol: TCP
  type: NodePort
