apiVersion: v1
kind: Service
metadata:
  name: auth-frontend-service
  namespace: auth-app
  labels:
    app: auth-frontend
spec:
  selector:
    app: auth-frontend
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 30001
    protocol: TCP
  type: NodePort
