name: Deploy Frontend to k3s

on:
  workflow_dispatch:

env:
  SERVER_IP: shivajshankar1.duckdns.org
  SSH_USER: ubuntu
  WORKING_DIR: /home/ubuntu/githubautomation_fe
  FRONTEND_IMAGE: diy-auth-frontend
  NAMESPACE: auth-app
  FRONTEND_URL: http://shivajshankar1.duckdns.org:3000
  BACKEND_URL: http://shivajshankar1.duckdns.org:8080
  K3S_DIR: /home/ubuntu/githubautomation_fe/deploy/k3s

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Create necessary directories on server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ env.SSH_USER }}@${{ env.SERVER_IP }} "
          mkdir -p ${{ env.WORKING_DIR }}/deploy/scripts
        "

    - name: Copy deployment script to server
      run: |
        # Make sure the local script exists
        if [ ! -f "./deploy/scripts/deploy_frontend.sh" ]; then
          echo "Error: deploy_frontend.sh not found locally"
          exit 1
        fi
        
        # Make the script executable
        chmod +x ./deploy/scripts/deploy_frontend.sh
        
        # Copy the script to the server
        scp -o StrictHostKeyChecking=no \
          ./deploy/scripts/deploy_frontend.sh \
          ${{ env.SSH_USER }}@${{ env.SERVER_IP }}:${{ env.WORKING_DIR }}/deploy/scripts/

    - name: Sync source code to server
      run: |
        # Create a clean copy of the repository
        mkdir -p /tmp/repo_sync
        cp -r . /tmp/repo_sync/
        
        # Remove unnecessary files to reduce transfer size
        rm -rf /tmp/repo_sync/.git
        rm -rf /tmp/repo_sync/node_modules
        
        # Sync the code to the server
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" \
          --delete \
          --exclude='.git' \
          --exclude='node_modules' \
          /tmp/repo_sync/ \
          ${{ env.SSH_USER }}@${{ env.SERVER_IP }}:${{ env.WORKING_DIR}}/
        
        # Clean up
        rm -rf /tmp/repo_sync

    - name: Set execute permissions on server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ env.SSH_USER }}@${{ env.SERVER_IP }} "
          cd ${{ env.WORKING_DIR }}
          chmod +x ./deploy/scripts/deploy_frontend.sh
        "

    - name: Copy frontend code to server
      run: |
        # First, copy all Kubernetes resources
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" \
          --exclude='.git' \
          --exclude='target' \
          --exclude='.mvn' \
          --exclude='.idea' \
          --exclude='*.iml' \
          --include='nodejs/loginscreen/**' \
          --include='deploy/k3s/' \
          --include='deploy/k3s/namespaces/' \
          --include='deploy/k3s/namespaces/*' \
          --include='deploy/k3s/configs/' \
          --include='deploy/k3s/configs/*' \
          --include='deploy/k3s/secrets/' \
          --include='deploy/k3s/secrets/*' \
          --include='deploy/k3s/deployments/' \
          --include='deploy/k3s/deployments/*' \
          --include='deploy/k3s/services/' \
          --include='deploy/k3s/services/*' \
          --include='deploy/k3s/ingresses/' \
          --include='deploy/k3s/ingresses/*' \
          --include='deploy/scripts/cleanup_k3s_images.sh' \
          --exclude='*' \
          . \
          ${{ env.SSH_USER }}@${{ env.SERVER_IP }}:${{ env.WORKING_DIR}}/

    - name: Clean up Docker environment for frontend
      run: |
        ssh -o StrictHostKeyChecking=no ${{ env.SSH_USER }}@${{ env.SERVER_IP }} "
          # Remove any existing frontend containers and images
          docker ps -a | grep ${{ env.FRONTEND_IMAGE }} | awk '{print \$1}' | xargs -r docker rm -f 2>/dev/null || true
          docker images | grep ${{ env.FRONTEND_IMAGE }} | awk '{print \$3}' | xargs -r docker rmi -f 2>/dev/null || true
          
          # Clean up any dangling images
          docker system prune -f
        "

    - name: Deploy Frontend
      run: |
        # Copy the script to the server and make it executable
        scp -o StrictHostKeyChecking=no \
          ./deploy/scripts/deploy_frontend.sh \
          ${{ env.SSH_USER }}@${{ env.SERVER_IP }}:${{ env.WORKING_DIR }}/deploy/scripts/
            
        # Run the deployment script on the server
        ssh -o StrictHostKeyChecking=no ${{ env.SSH_USER }}@${{ env.SERVER_IP }} "
          cd ${{ env.WORKING_DIR }}
          chmod +x ./deploy/scripts/deploy_frontend.sh
          
          # Set environment variables and run the script
          NAMESPACE='${{ env.NAMESPACE }}' \
          WORKING_DIR='${{ env.WORKING_DIR }}' \
          FRONTEND_IMAGE='${{ env.FRONTEND_IMAGE }}' \
          K3S_DIR='${{ env.K3S_DIR }}' \
          FRONTEND_URL='${{ env.FRONTEND_URL }}' \
          BACKEND_URL='${{ env.BACKEND_URL }}' \
          ./deploy/scripts/deploy_frontend.sh
          
          # Force rollout of the deployment to ensure new image is used
          sudo k3s kubectl -n ${{ env.NAMESPACE }} rollout restart deployment/auth-frontend
          sudo k3s kubectl -n ${{ env.NAMESPACE }} rollout status deployment/auth-frontend --timeout=120s
        "

    - name: Verify frontend deployment
      run: |
        echo "=== Verifying Frontend Deployment ==="
        echo "Frontend URL: ${{ env.FRONTEND_URL }}"
        
        # Simple health check
        echo -n "Frontend status: "
        curl -s -o /dev/null -w "%{http_code}" ${{ env.FRONTEND_URL }} || echo "unreachable"
        echo -e "\nFrontend deployment completed successfully!"
